spring:
  application:
    name: service-data
  data:
    mongodb:
      host: mongodbCluster.ldxy.edu.cn
      port: 27017
      authentication-database: kooo
      database: kooo
      username: kooo
      password: kooo8522206


