eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
server:
  port: 9030


spring:
  application:
    name: auth2.0-center
  data:
    mongodb:
      host: mongodbCluster.ldxy.edu.cn
      port: 27017
      authentication-database: kooo
      database: kooo
      username: kooo
      password: kooo8522206
  zipkin:
      base-url: http://localhost:9050
  redis:
    host: 59.76.48.138
    port: 6379
    password: kooo8522206
  security:
    oauth2:
      client:
        access-token-uri: http://localhost:${server.port}/oauth/token
        user-authorization-uri: http://localhost:${server.port}/oauth/authorize


endpoints:
  health:
    enable: true
management:
  security:
    enable: false

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration

feign:
  hystrix:
    enabled: false