eureka:
  client:
   # register-with-eureka: false
  #  fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/

server:
  port: 9020
spring:
  application:
    name: service-ribbon
